// resources/js/Components/Backend/TalentDashboard/Calendar/CalendarPreview/index.vue
<template>
  <div class="cover_photo wrapper h-full relative">
    <div 
      class="calendar shadow" 
      :class="(getPage.name !== 'cover' && getPage.name !== 'back') ? 'h-[60%]' : 'h-full'"
      id='calendar_main_wrapper'
    >
      <img 
        v-if="!isEmpty(getPage.path)"
        class="back_image h-full w-full block object-cover object-center"
        :src="getPage.path"
        alt='' 
      />
      <MoveableBox />
    </div>
    <Calendar v-if="getPage.name !== 'cover' && getPage.name !== 'back'" />
  </div>
</template>

<script setup>
  import useCalendar from '@/Components/Backend/TalentDashboard/Calendar/useCalendar.js'
  import Calendar from '@/Components/Backend/TalentDashboard/Calendar/CalendarPreview/Calendar.vue'
  import MoveableBox from '@/Components/Backend/TalentDashboard/Calendar/MoveableBox/index.vue'
  import { isEmpty } from 'lodash'

  const { getPage } = useCalendar()
</script>

<style scoped>
.wrapper{
  background-color: #fff;
  width: 500px;
  height: 800px;
  margin: auto;
  aspect-ratio: 1/1.6;
  overflow: hidden;
}
.calendar{
  background-color: #fff;
}
.body{
  height: 100%;
}
.calendar .image{
  height: 60%;
  background-color: #fff;
}
.calendar .image img{
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.cover_image,
.back_image{
  aspect-ratio: 1/1.4;
  object-fit: cover;
}
</style>


<!-- import classes from './index.module.css'
import { listOfMonth } from '../../../calendarData';
import useCalendar from '../useCalendar';
import { useContext } from 'react';
import calendarContext from '../../../context/calendarContext';
import { useRef } from 'react';
import { useEffect } from 'react';
import MoveableBox from '../MoveableBox'
import { get } from 'lodash'


const CalendarPreview = ({ img, style={}, selectedMonth, selectedYear }) =>
{
  const calendarContainer = useRef()
  const { getDateList } = useCalendar()
  const { calendarTheme, setCalendarContainerElement, language, weeks } = useContext(calendarContext)
  useEffect(() => {
    setCalendarContainerElement(calendarContainer.current)
  })

  return (
    <div className={ [classes.wrapper, 'h-full'].join(' ') } ref={ calendarContainer } style={style}>
      <div className={ [classes.calendar, 'shadow h-full relative'].join(' ') } id='calendar_main_wrapper'>
        <MoveableBox style={ get(img, 'text.style') } title={ get(img, 'text.title') } />
        <div className={ [classes.image].join(' ') }>
          {
            img && img.path != '' &&
            <img 
              className='block w-full object-cover object-center'
              src={ img.path }
              alt=""
            />
          }
        </div>

        <div className={ [ classes.body, calendarTheme === 'black' && 'bg-gray-800 text-white' ].join(' ') }>
          <div className='flex justify-between items-end px-6 py-4' style={ {backgroundColor: '#9992'} }>
            <div className='font-medium italic text-xl capitalize'>{ listOfMonth[selectedMonth][language] }</div>
            <div className='text-orangered-500 font-bold text-red-400 italic text-3xl'>{ selectedYear }</div>
          </div>

          <div className={ ['p-4 pt-0 text-xs'].join(' ') }>
            <div className='grid grid-cols-7'>
              {
                weeks[language].map(week => (
                  <span key={ week } className={ [classes.cell, 'text-semibold text-center px-2 py-2'].join(' ') }>
                    { week.slice(0, 3) }
                  </span>
                ))
              }
            </div>

            <div className='grid grid-cols-7'>
              {
                getDateList(selectedMonth, selectedYear).map((item, index) => (
                  <span 
                    className={ [
                      classes.cell,
                      item.isInactive&&'opacity-30',
                      item.isActive&&'bg-red-400 font-bold',
                      'text-center px-2 py-2'
                    ].join(' ') } 
                    key={ 'cellKey-'+index }
                  >
                  {item.isActive}
                    { item.date }
                  </span>
                ))
              }
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}


export default CalendarPreview -->

// resources/js/Components/Backend/TalentDashboard/Calendar/CalendarPreview/index.jsx
import classes from './index.module.css'
import { listOfMonth } from '../../../calendarData';
import useCalendar from '../useCalendar';
import { useContext } from 'react';
import calendarContext from '../../../context/calendarContext';
import { useRef } from 'react';
import { useEffect } from 'react';
import MoveableBox from '../MoveableBox'
import { get } from 'lodash'


const CalendarPreview = ({ img, style={}, selectedMonth, selectedYear }) =>
{
  const calendarContainer = useRef()
  const { getDateList } = useCalendar()
  const { calendarTheme, setCalendarContainerElement, language, weeks } = useContext(calendarContext)
  useEffect(() => {
    setCalendarContainerElement(calendarContainer.current)
  })

  return (
    <div className={ [classes.wrapper, 'h-full'].join(' ') } ref={ calendarContainer } style={style}>
      <div className={ [classes.calendar, 'shadow h-full relative'].join(' ') } id='calendar_main_wrapper'>
        <MoveableBox style={ get(img, 'text.style') } title={ get(img, 'text.title') } />
        <div className={ [classes.image].join(' ') }>
          {
            img && img.path != '' &&
            <img 
              className='block w-full object-cover object-center'
              src={ img.path }
              alt=""
            />
          }
        </div>

        <div className={ [ classes.body, calendarTheme === 'black' && 'bg-gray-800 text-white' ].join(' ') }>
          <div className='flex justify-between items-end px-6 py-4' style={ {backgroundColor: '#9992'} }>
            <div className='font-medium italic text-xl capitalize'>{ listOfMonth[selectedMonth][language] }</div>
            <div className='text-orangered-500 font-bold text-red-400 italic text-3xl'>{ selectedYear }</div>
          </div>

          <div className={ ['p-4 pt-0 text-xs'].join(' ') }>
            <div className='grid grid-cols-7'>
              {
                weeks[language].map(week => (
                  <span key={ week } className={ [classes.cell, 'text-semibold text-center px-2 py-2'].join(' ') }>
                    { week.slice(0, 3) }
                  </span>
                ))
              }
            </div>

            <div className='grid grid-cols-7'>
              {
                getDateList(selectedMonth, selectedYear).map((item, index) => (
                  <span 
                    className={ [
                      classes.cell,
                      item.isInactive&&'opacity-30',
                      item.isActive&&'bg-red-400 font-bold',
                      'text-center px-2 py-2'
                    ].join(' ') } 
                    key={ 'cellKey-'+index }
                  >
                  {item.isActive}
                    { item.date }
                  </span>
                ))
              }
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}


export default CalendarPreview
